import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import { CartProvider } from './context-cart/context-cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'שוק האלכוהול',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
        <Navbar/>
        {children}
        <Footer/>
      </CartProvider>
        </body>
    </html>
  )
}
