export const cocktails = [
  {
    name: "אפרול ספריץ",
    description:
      "קוקטייל איטלקי מרענן שנעשה עם אפרול, פרוסקו, ומים סודה, מקושט בפרות תפוח האדמה.",
    price: 12.99,
    discountedPrice: 10.99,
    image: "/coctails/coctail1.webp",
    slug: "aperol-spritz",
  },
  {
    name: "קוקטייל שמפניה",
    description:
      "קוקטייל אלגנטי שנעשה עם שמפניה, סוכר, ג'ינג'ר אנגוסטורה, ופירות תפוח לימון.",
    price: 14.99,
    discountedPrice: 12.99,
    image: "/coctails/coctail2.webp",
    slug: "champagne-cocktail",
  },
  {
    name: "קוסמופוליטן",
    description:
      "קוקטייל קלאסי הכולל וודקה, מיץ קרנברי, טריפל סק, ומיץ מליח טרי, שמונשם עם קרח ונזל.",
    price: 11.99,
    discountedPrice: 9.99,
    image: "/coctails/coctail3.webp",
    slug: "cosmopolitan",
  },
  {
    name: "דייקירי",
    description:
      "קוקטייל פשוט עוד טעים שנעשה עם רום, מיץ לימון, וסירופ פשוט, מוגש ישר או על הקרח.",
    price: 10.99,
    discountedPrice: 8.99,
    image: "/coctails/coctail4.webp",
    slug: "daiquiri",
  },
  {
    name: "פרנץ' 75",
    description: "קוקטייל מרומם שנעשה עם ג'ין, שמפניה, מיץ לימון, וסוכר.",
    price: 13.99,
    discountedPrice: 11.99,
    image: "/coctails/coctail5.webp",
    slug: "french-75",
  },
  {
    name: "ג'ין פיז",
    description:
      "קוקטייל מרענן שנעשה עם ג'ין, מיץ לימון, סוכר, ומים סודה, מוגש מעל קרח.",
    price: 11.99,
    discountedPrice: 9.99,
    image: "/coctails/coctail6.webp",
    slug: "gin-fizz",
  },
  {
    name: "ג'ין טוניק",
    description: "קוקטייל קלאסי עשוי ג'ין ומים טוניק, מוגש עם קליפת לימון.",
    price: 9.99,
    discountedPrice: 7.99,
    image: "/coctails/coctail7.webp",
    slug: "gin-tonic",
  },
  {
    name: "מוג'יטו",
    description:
      "קוקטייל קובני עשוי רום לבן, סוכר, מיץ לימון, מים סודה, ועלי נענע, מוגש מעל קרח.",
    price: 12.99,
    discountedPrice: 10.99,
    image: "/coctails/coctail8.webp",
    slug: "mojito",
  },
  {
    name: "מוסקו מול",
    description:
      "קוקטייל מרענן שנעשה עם וודקה, בירת זנג'ר, ומיץ לימון, מקושט בקליפת לימון.",
    price: 10.99,
    discountedPrice: 8.99,
    image: "/coctails/coctail9.webp",
    slug: "moscow-mule",
  },
  {
    name: "אולד פאשנד",
    description:
      "קוקטייל קלאסי שנעשה עם ויסקי, סוכר, אנגוסטורה ביטרס, וקליפת תפוז.",
    price: 13.99,
    discountedPrice: 11.99,
    image: "/coctails/coctail10.webp",
    slug: "old-fashioned",
  },
  {
    name: "פלומה",
    description:
      "קוקטייל מקסיקני עשוי טקילה, סודת ענבים, מיץ לימון, ורמז של מלח.",
    price: 11.99,
    discountedPrice: 9.99,
    image: "/coctails/coctail11.webp",
    slug: "paloma",
  },
  {
    name: "פטרון מרגריטה",
    description:
      "מרגריטה פרימיום שנעשית עם טקילה פטרון, טריפל סק, ומיץ לימון טרי, מוגשת על הקרח עם פינוק ממלח.",
    price: 150.99,
    discountedPrice: 13.99,
    image: "/coctails/coctail12.webp",
    slug: "patron-margarita",
  },
  {
    name: "טום קולינז'",
    description:
      "קוקטייל ג'ין קלאסי שנעשה עם ג'ין, מיץ לימון, סוכר, ומים סודה, מוגש מעל קרח ומקושט בדובדבן ופרח תפוז.",
    price: 11.99,
    discountedPrice: 9.99,
    image: "/coctails/coctail13.webp",
    slug: "tom-collins",
  },
  {
    name: "וויסקי סאוור",
    description:
      "קוקטייל חמוץ שנעשה עם ויסקי, מיץ לימון, וסירופ פשוט, נקרר עם קרח ומסונן לכוס.",
    price: 12.99,
    discountedPrice: 10.99,
    image: "/coctails/coctail14.webp",
    slug: "whiskey-sour",
  },
];

export const whiskys = [
  {
    name: "אודיסיאה של ג'וני ווקר",
    slug: "johnnie-walker-odessey",
    description:
      "אודיסיאה היא גרסה משודרגת של וויסקי ג'וני ווקר, המייצגת את המסע של ייצור הוויסקי. מיוצרת בתשומת לב מדוקדקת, היא משלבת את השעורה והדגנים האיכותיים ביותר ליצירת פרופיל טעמים עשיר ומורכב. עם תווי וניל ואלון, הניחוח שלה מזמין ומפנק, מבטיח הרפתקה חושית בכל לשיחה.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "119",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "ניחוח עשיר ופירותי עם הפכים של וניל ואלון.",
    image: "/whisky/whisky1.webp",
  },
  {
    name: "מלך ג'ורג' החמישי",
    slug: "king-george-v",
    description:
      "ראוי למלכות, מלך ג'ורג' החמישי הוא ביטוי של מקצועיות בייצור הוויסקי. במיזוג דיוקני של שעורה ודגנים, הוא מציע פלטת טעמים מורכבת המאופיינת בתווי פירות יבשים, תבלינים, ועשן עדין. הניחוח שלו מורכב וחזק, מזמין לתהליך גורמה ופריבילגי עליון.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "40",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "מורכב וחזק עם תווי פירות יבשים, תבלינים ועשן.",
    image: "/whisky/whisky2.webp",
  },
  {
    name: "ג'וני ווקר בלואייבל כחול",
    slug: "johnnie-walker-blue-label-ghost",
    description:
      "מהדורה מיוחדת של ג'וני ווקר בלואייבל, הוויסקי הזה מציע חוויה עדינה ומתוחכמת. עם תווי דבש, אגוזים, ותאנים, הניחוח שלו משדר עדינות ורומנטיקה, מזמין את החושים למסע של גילוי והנאה.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "40",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "עדין ומעודן עם הפכים של דבש, אגוזים וטורפים.",
    image: "/whisky/whisky3.webp",
  },
  {
    name: "ריזרב גולד לייבל",
    slug: "gold-label-reserve",
    description:
      "גרסה מפנקת של וויסקי. חלק וקרמי עם הפכים של דבש, וניל וקרמל.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "280",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "חלק וקרמי עם הפכים של דבש, וניל וקרמל.",
    image: "/whisky/whisky4.webp",
  },
  {
    name: "ג'וני ווקר בלאק לייבל",
    slug: "johnnie-walker-black-label",
    description:
      "וויסקי קלאסי ואייקוני. גוף מלא עם הפכים של עשן, פירות ותבלינים.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "150",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "גוף מלא עם הפכים של עשן, פירות ותבלינים.",
    image: "/whisky/whisky5.webp",
  },
  {
    name: "ג'וני ווקר 18 שנים",
    slug: "johnnie-walker-18-years",
    description:
      "מבוגר למשך 18 שנים, מציע איכות יוצאת דופן. עשיר ומורכב עם הפכים של פירות כהים, טופי ואלון.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "280",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "עשיר ומורכב עם הפכים של פירות כהים, טופי ואלון.",
    image: "/whisky/whisky6.webp",
  },
  {
    name: "ג'וני ווקר דאבל בלאק",
    slug: "johnnie-walker-double-black",
    description:
      "מהדורה אינטנסיבית ועשירה של וויסקי ג'וני ווקר. עישניות אינטנסיבית עם הפכים של תבלינים ופירות יבשים.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "119",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "עישניות אינטנסיבית עם הפכים של תבלינים ופירות יבשים.",
    image: "/whisky/whisky7.webp",
  },
  {
    name: "ג'וני ווקר בטמן לולנדס",
    slug: "johnnie-walker-batman-lowlands",
    description:
      "מהדורת מיוחדת של וויסקי מאושרת על ידי באטמן. אפל ומסתורי עם הפכים של שוקולד, תבלינים ולימון.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "119",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "אפל ומסתורי עם הפכים של שוקולד, תבלינים ולימון.",
    image: "/whisky/whisky8.webp",
  },
  {
    name: "צ'יוויס ריגל 12",
    slug: "chivas-regal-12",
    description:
      "מיקס חלק ומאוזן של וויסקי. פירותי עם הפכים של דבש, וניל וצמחים.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "150",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "פירותי עם הפכים של דבש, וניל וצמחים.",
    image: "/whisky/whisky9.webp",
  },
  {
    name: "צ'יוויס ריגל 150",
    slug: "chivas-regal-150",
    description:
      "וויסקי עשיר וקרמי עם טעם מתוק. עשיר עם הפכים של דבש, אגוזים ותבלינים.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "119",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "עשיר עם הפכים של דבש, אגוזים ותבלינים.",
    image: "/whisky/whisky10.webp",
  },
  {
    name: "צ'יוויס ריגל 18",
    slug: "chivas-regal-18",
    description:
      "וויסקי מפואר ומורכב מבוגר למשך 18 שנים. עם תווים של שוקולד כהה, תבלינים, ופירות, הוא מציע חוויה עשירה ומעוררת.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "280",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "חלק ומודהם עם הפכים של שוקולד כהה, תבלינים ופירות.",
    image: "/whisky/whisky11.webp",
  },
  {
    name: "בלנטייןס 12 שנים",
    slug: "ballantines-12-years",
    description:
      "וויסקי חלק ומאוזן מבוגר למשך 12 שנים. עם תווים של דבש, וניל, ואלון, הוא מציע חוויה נעימה ומרעננת.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "150",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "רך ונעים עם הפכים של דבש, וניל ואלון.",
    image: "/whisky/whisky12.webp",
  },
  {
    name: "בלנטייןס 17 שנים",
    slug: "ballantines-17-years",
    description:"וויסקי פרימיום מבוגר למשך 17 שנים, המציע עומק ומורכבות. עם תווים של טופי, תבלינים, ואלון, הוא מציע חוויה עשירה ומלאה.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "119",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "עשיר וגוף מלא עם הפכים של טופי, תבלינים ואלון.",
    image: "/whisky/whisky13.webp",
  },
  {
    name: "דיווארס ווייט לייבל",
    slug: "dewars-white-label",
    description:"וויסקי קלאסי וחלק עם היסטוריה עשירה. עם תווים של דבש, וניל, ואלון, הוא מציע חוויה מרעננת ומתקתקת.",
    ingredients: ["שעורת שיבולת שועל", "דגנים"],
    price: "150",
    size: "750 מל",
    spirit_type: "וויסקי סקוט' מעורב",
    origin_country: "סקוטלנד",
    smell: "קליל ופרחוני עם הפכים של דבש, וניל ואלון.",
    image: "/whisky/whisky14.webp",
  },
];

export const products = [
  {
    name: "וויסקי 1888 גראן רזרב 700 מל",
    price: " ₪ 125.00",
    image: "/images/bottle1.webp",
    id: "1",
  },
  {
    name: "וויסקי 1888 גראן רזרב 700 מל",
    price: " ₪ 125.00",
    image: "/images/bottle2.webp",
    id: "2",
  },
  {
    name: "וויסקי 1888 גראן רזרב 700 מל",
    price: " ₪ 125.00",
    image: "/images/bottle3.webp",
    id: "3",
  },
  {
    name: "וויסקי 1888 גראן רזרב 700 מל",
    price: " ₪ 125.00",
    image: "/images/bottle4.webp",
    id: "4",
  },
];